[2024-03-17T00:27:34.622+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab2.build_save_model_task manual__2024-03-17T00:27:28.469619+00:00 [queued]>
[2024-03-17T00:27:34.628+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab2.build_save_model_task manual__2024-03-17T00:27:28.469619+00:00 [queued]>
[2024-03-17T00:27:34.628+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-17T00:27:34.628+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-03-17T00:27:34.629+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-17T00:27:34.635+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2024-03-17 00:27:28.469619+00:00
[2024-03-17T00:27:34.640+0000] {standard_task_runner.py:55} INFO - Started process 1311 to run task
[2024-03-17T00:27:34.642+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab2', 'build_save_model_task', 'manual__2024-03-17T00:27:28.469619+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpbr5gny3w']
[2024-03-17T00:27:34.643+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask build_save_model_task
[2024-03-17T00:27:34.674+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow_Lab2.build_save_model_task manual__2024-03-17T00:27:28.469619+00:00 [running]> on host d8b0252a8521
[2024-03-17T00:27:34.718+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Airflow_Lab2
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-17T00:27:28.469619+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-17T00:27:28.469619+00:00
[2024-03-17T00:27:34.723+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/model_development.py", line 68, in build_model
    pickle.dump(lr_clf, open(output_path, 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/../model/model.sav'
[2024-03-17T00:27:34.727+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Airflow_Lab2, task_id=build_save_model_task, execution_date=20240317T002728, start_date=20240317T002734, end_date=20240317T002734
[2024-03-17T00:27:34.734+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task build_save_model_task ([Errno 2] No such file or directory: '/opt/airflow/dags/src/../model/model.sav'; 1311)
[2024-03-17T00:27:34.739+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-03-17T00:27:34.754+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
